#!/usr/bin/env bash
SCRIPT_DIR="${BASH_SOURCE[0]%/*}"
case $SCRIPT_DIR in
    $HOME/.config/*)
        echo Do not run this script from inside $HOME/.config. EXITING...
        echo For instance put hdots folder inside $HOME/.local/share/ or other location and run install.sh from there.
        exit 1
        ;;
esac

symlinks=(
    $HOME/.config/hdots:$SCRIPT_DIR
    $HOME/hypr-bin:$HOME/.config/hdots/hypr-bin
    $HOME/.config/hypr:$HOME/.config/hdots/.config/hypr
)
for pair in ${symlinks[@]}; do
    l=${pair%%:*}   # part before :
    r=${pair##*:}   # part after :
    mkdir -p $(dirname $l)
	mkdir -p $r
	[ "$(readlink -f $l)" = "$(readlink -f $r)" ] || {
		mv $l $l.$RANDOM.delme 2>/dev/null
		ln -s $r $l
	}
done


# prepare bashrc
L='[ -e $hypr_sources/env ] && . $hypr_sources/env || . ~/.config/hdots/sources/env'
grep -qxF "$L" ~/.bashrc || {
    cp ~/.bashrc ~/.bashrc.$RANDOM.bak
    printf "%s\n%s\n" "$L" "$(cat ~/.bashrc)" > ~/.bashrc
}

# prepare .profile
grep -qxF '. ~/.bashrc' ~/.profile || {
    cp ~/.profile ~/.profile.$RANDOM.bak
    printf "%s\n%s\n" '. ~/.bashrc' "$(cat ~/.profile)" > ~/.profile
}


grep -qxF '~/.config/hdots/launch_bins/hypr_auto' ~/.bashrc || {
    echo "~/.config/hdots/launch_bins/hypr_auto # auto launch hyprland at first boot alwayas at last" >> ~/.bashrc
}


mkdir -p $HOME/.config/hypr
# prepare hyprland.conf
grep -qxF 'hl.exec_cmd("/home/tw/.config/hdots/launch_bins/prelaunch")' ~/.config/hypr/hyprland.lua || {
cat <<EOF > ~/.config/hypr/hyprland.lua
-- Generated by hyprland_main_config_gen, do not edit this file put your changes in overrides.lua
hl.on("hyprland.start", function ()
hl.exec_cmd("$HOME/.config/hdots/launch_bins/prelaunch")
end)
require('configs/secondary')
require('configs/general')
require('configs/border')
require('configs/blur')
require('configs/shadow')
require('configs/opacity')
require('configs/shader')
require('keybinds')
require('overrides')
EOF
}


echo "All linking logic finished"
