//! Config file support — parse the rconfig-expanded `zov/config`.
//!
//! The live file is generated by the hdots pipeline
//! (`sources/templates/zov/config` → `rconfig_gen` → `~/.config/zov/config`),
//! which expands `$fg`/`$bg`/`$acc`-style theme globals into plain INI:
//!
//! ```ini
//! [theme]
//! backdrop        = #2e3440ff
//! selection       = #E84E4E
//! [layout]
//! font            = Satoshi Variable
//! gap             = 8
//! [keys]
//! Escape          = hide
//! Super+Left      = activate
//! ```
//!
//! Missing file / missing keys are fine: everything falls back to the
//! built-in `Theme::default()` values and `hypr::KeyAction::resolve`, so a
//! partial or absent config never breaks the overlay.

use smithay_client_toolkit::seat::keyboard::Keysym;

use crate::render::Theme;

/// What a configured key press does. Mirrors `hypr::KeyAction` but is
/// constructible from config text.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ConfigAction {
    Hide,
    Scroll(i64),
    MoveSel(i32),
    MoveRow(i32),
    Activate,
}

/// A key binding as written: optional `Super+` prefix + a keysym.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct KeySpec {
    pub logo: bool,
    pub keysym: Keysym,
}

#[derive(Debug, Clone, Default)]
pub struct Config {
    /// Raw `[theme]` values, keyed by lower-cased name (`backdrop`, `selection`, …).
    pub theme: std::collections::HashMap<String, String>,
    /// Raw `[layout]` values (`font`, `font_size`, `gap`, `tile_radius`).
    pub layout: std::collections::HashMap<String, String>,
    /// `[keys]` bindings in file order; first match wins.
    pub keys: Vec<(KeySpec, ConfigAction)>,
}

impl From<ConfigAction> for crate::hypr::KeyAction {
    fn from(a: ConfigAction) -> Self {
        match a {
            ConfigAction::Hide => crate::hypr::KeyAction::Hide,
            ConfigAction::Scroll(n) => crate::hypr::KeyAction::ScrollToWs(n),
            ConfigAction::MoveSel(d) => crate::hypr::KeyAction::MoveSel(d),
            ConfigAction::MoveRow(d) => crate::hypr::KeyAction::MoveRow(d),
            ConfigAction::Activate => crate::hypr::KeyAction::Activate,
        }
    }
}

/// KP_Enter is the numpad twin of Return — normalize so one `[keys]` entry
/// covers both.
fn normalize(ks: Keysym) -> Keysym {
    if ks == Keysym::KP_Enter {
        Keysym::Return
    } else {
        ks
    }
}

/// Digit keysym → its number (Keysym::_1 → 1), else None.
fn digit_of(ks: Keysym) -> Option<i64> {
    let n = ks.raw().checked_sub(Keysym::_1.raw())?;
    (n < 9).then(|| n as i64 + 1)
}

/// True for the physical Super/Logo keys (either side, Meta included — some
/// keymaps map the Windows key to Meta). zov tracks the modifier from raw key
/// press/release in addition to the compositor's Modifiers event, which some
/// builds deliver late (or not at all) mid-grab.
pub fn is_super_key(ks: Keysym) -> bool {
    matches!(
        ks,
        Keysym::Super_L | Keysym::Super_R | Keysym::Meta_L | Keysym::Meta_R
    )
}

/// True for the raw evdev keycodes of the Super/Meta keys (KEY_LEFTMETA =
/// 125, KEY_RIGHTMETA = 126; Wayland delivers them +8). Fixed constants of
/// the Linux evdev protocol — used to scan the pressed-key list of the
/// keyboard enter event, which is how zov detects Super held from BEFORE the
/// grab (the SUPER+Tab open: the press itself was never delivered to us).
pub fn is_super_keycode(code: u32) -> bool {
    code == 125 + 8 || code == 126 + 8
}

fn keysym_of(name: &str) -> Option<Keysym> {
    let n = name.trim().to_ascii_lowercase();
    Some(match n.as_str() {
        "escape" => Keysym::Escape,
        "return" | "enter" | "kp_enter" => Keysym::Return,
        "space" => Keysym::space,
        "left" => Keysym::Left,
        "right" => Keysym::Right,
        "up" => Keysym::Up,
        "down" => Keysym::Down,
        "tab" => Keysym::Tab,
        "1" => Keysym::_1,
        "2" => Keysym::_2,
        "3" => Keysym::_3,
        "4" => Keysym::_4,
        "5" => Keysym::_5,
        "6" => Keysym::_6,
        "7" => Keysym::_7,
        "8" => Keysym::_8,
        "9" => Keysym::_9,
        _ => return None,
    })
}

fn action_of(value: &str, keysym: Keysym) -> Option<ConfigAction> {
    Some(match value.trim().to_ascii_lowercase().as_str() {
        "hide" => ConfigAction::Hide,
        "activate" => ConfigAction::Activate,
        // The workspace number comes from the key (1..9), not the value.
        "scroll_to_ws" | "scrolltows" => ConfigAction::Scroll(digit_of(keysym).unwrap_or(1)),
        "move_sel_left" => ConfigAction::MoveSel(-1),
        "move_sel_right" => ConfigAction::MoveSel(1),
        "move_row_up" => ConfigAction::MoveRow(-1),
        "move_row_down" => ConfigAction::MoveRow(1),
        _ => return None,
    })
}

fn parse_key(name: &str, value: &str) -> Option<(KeySpec, ConfigAction)> {
    let (logo, base) = match name.split_once('+') {
        Some((modifier, rest)) => (
            modifier.trim().eq_ignore_ascii_case("super")
                || modifier.trim().eq_ignore_ascii_case("logo"),
            rest,
        ),
        None => (false, name),
    };
    let keysym = keysym_of(base)?;
    let action = action_of(value, keysym)?;
    Some((KeySpec { logo, keysym }, action))
}

/// `#rrggbb` / `#rrggbbaa` → 0xRRGGBB. The renderer paints opaque, so a
/// trailing alpha component is accepted but ignored (hdots `$bg8`-style
/// values arrive as RRGGBBAA — alpha last).
pub fn parse_color(v: &str) -> Option<u32> {
    let hex = v.trim().trim_start_matches('#');
    let hex = if hex.len() >= 6 { &hex[..6] } else { hex };
    if hex.len() != 6 || !hex.chars().all(|c| c.is_ascii_hexdigit()) {
        return None;
    }
    u32::from_str_radix(hex, 16).ok()
}

impl Config {
    /// Canonical live path: `$XDG_CONFIG_HOME/zov/config` else
    /// `$HOME/.config/zov/config` — exactly where rconfig_gen writes it.
    pub fn path() -> std::path::PathBuf {
        if let Ok(xdg) = std::env::var("XDG_CONFIG_HOME") {
            if !xdg.is_empty() {
                return std::path::PathBuf::from(xdg).join("zov/config");
            }
        }
        let home = std::env::var("HOME").unwrap_or_default();
        std::path::PathBuf::from(home).join(".config/zov/config")
    }

    /// Parse the live config; any error (missing, unreadable) yields the
    /// all-default Config — the overlay must always come up.
    pub fn load() -> Self {
        Self::from_file(&Self::path()).unwrap_or_default()
    }

    pub fn from_file(path: &std::path::Path) -> Option<Self> {
        let text = std::fs::read_to_string(path).ok()?;
        Some(Self::parse(&text))
    }

    pub fn parse(text: &str) -> Self {
        let mut cfg = Config::default();
        let mut section = String::new();
        for raw in text.lines() {
            let line = raw.trim();
            if line.is_empty() || line.starts_with('#') || line.starts_with(';') {
                continue;
            }
            if line.starts_with('[') && line.ends_with(']') {
                section = line[1..line.len() - 1].trim().to_ascii_lowercase();
                continue;
            }
            let Some((k, v)) = line.split_once('=') else {
                continue;
            };
            let (k, v) = (k.trim(), v.trim());
            if k.is_empty() || v.is_empty() {
                continue;
            }
            match section.as_str() {
                "theme" => {
                    cfg.theme.insert(k.to_ascii_lowercase(), v.to_string());
                }
                "layout" => {
                    cfg.layout.insert(k.to_ascii_lowercase(), v.to_string());
                }
                "keys" => {
                    if let Some(entry) = parse_key(k, v) {
                        cfg.keys.push(entry);
                    }
                }
                _ => {}
            }
        }
        cfg
    }

    /// Look up a pressed key. `logo` is the Super modifier state zov tracks
    /// itself (the grabbed keyboard bypasses Hyprland's binds).
    pub fn resolve(&self, keysym: Keysym, logo: bool) -> Option<ConfigAction> {
        let pressed = normalize(keysym);
        self.keys
            .iter()
            .find(|(spec, _)| spec.logo == logo && normalize(spec.keysym) == pressed)
            .map(|(_, action)| *action)
    }

    pub fn f32_or(&self, key: &str, default: f32) -> f32 {
        self.layout
            .get(key)
            .and_then(|v| v.parse::<f32>().ok())
            .filter(|f| *f > 0.0)
            .unwrap_or(default)
    }

    /// Font family for the renderer; falls back to the renderer's "Sans".
    pub fn font_family(&self) -> String {
        self.layout
            .get("font")
            .filter(|f| !f.is_empty())
            .cloned()
            .unwrap_or_else(|| "Sans".into())
    }

    /// Append the built-in rofi-style bindings for any key the user's `[keys]`
    /// section does not already cover. Called once at startup with the loaded
    /// config, so configured entries win and unlisted keys keep the defaults
    /// (Escape/arrows/Enter/space, Super+arrows jump, digits scroll).
    pub fn seed_builtins(&mut self) {
        let defaults: [(bool, &str, ConfigAction); 9] = [
            (false, "Escape", ConfigAction::Hide),
            (false, "Left", ConfigAction::MoveSel(-1)),
            (false, "Right", ConfigAction::MoveSel(1)),
            (false, "Up", ConfigAction::MoveRow(-1)),
            (false, "Down", ConfigAction::MoveRow(1)),
            (false, "Return", ConfigAction::Activate),
            (false, "space", ConfigAction::Activate),
            (true, "Left", ConfigAction::Activate),
            (true, "Right", ConfigAction::Activate),
        ];
        for (logo, name, action) in defaults {
            let Some(ks) = keysym_of(name) else { continue };
            if self
                .keys
                .iter()
                .any(|(s, _)| s.logo == logo && normalize(s.keysym) == normalize(ks))
            {
                continue;
            }
            self.keys.push((KeySpec { logo, keysym: ks }, action));
        }
        for d in 1..=9i64 {
            let Some(ks) = keysym_of(&d.to_string()) else { continue };
            if self
                .keys
                .iter()
                .any(|(s, _)| !s.logo && normalize(s.keysym) == normalize(ks))
            {
                continue;
            }
            self.keys
                .push((KeySpec { logo: false, keysym: ks }, ConfigAction::Scroll(d)));
        }
    }

    /// Overlay the `[theme]` section onto a `Theme` (which starts from
    /// built-in defaults). Unknown names are skipped.
    pub fn apply_theme(&self, theme: &mut Theme) {
        let fields: [(&str, &mut u32); 14] = [
            ("backdrop", &mut theme.backdrop),
            ("row_bg", &mut theme.row_bg),
            ("row_bg_active", &mut theme.row_bg_active),
            ("row_border", &mut theme.row_border),
            ("row_border_active", &mut theme.row_border_active),
            ("label", &mut theme.label),
            ("label_active", &mut theme.label_active),
            ("tile_bg", &mut theme.tile_bg),
            ("tile_bg_active", &mut theme.tile_bg_active),
            ("tile_border", &mut theme.tile_border),
            ("tile_border_active", &mut theme.tile_border_active),
            ("title", &mut theme.title),
            ("class", &mut theme.class),
            ("selection", &mut theme.selection),
        ];
        for (name, field) in fields {
            if let Some(v) = self.theme.get(name) {
                if let Some(c) = parse_color(v) {
                    *field = c;
                }
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const SAMPLE: &str = r#"
# zov — expanded from $states2 by rconfig_gen

[theme]
backdrop        = #2e3440ff
row_bg          = #444a55
selection       = #E84E4E
title           = #eceff4

[layout]
font            = Satoshi Variable
font_size       = 14
gap             = 8
tile_radius     = 8

[keys]
Escape          = hide
1               = scroll_to_ws
5               = scroll_to_ws
Left            = move_sel_left
Right           = move_sel_right
Up              = move_row_up
Down            = move_row_down
Return          = activate
KP_Enter        = activate
space           = activate
Super+Left      = activate
Super+Right     = activate
"#;

    #[test]
    fn parses_theme_layout_and_keys() {
        let cfg = Config::parse(SAMPLE);
        assert_eq!(cfg.theme.get("selection").unwrap(), "#E84E4E");
        assert_eq!(cfg.font_family(), "Satoshi Variable");
        assert_eq!(cfg.f32_or("gap", 14.0), 8.0);
        assert_eq!(cfg.f32_or("tile_radius", 8.0), 8.0);
        // 12 key lines, all parse
        assert_eq!(cfg.keys.len(), 12);
    }

    #[test]
    fn colors_six_and_eight_digit() {
        assert_eq!(parse_color("#2e3440"), Some(0x2e3440));
        // RRGGBBAA — alpha suffix ignored (renderer paints opaque)
        assert_eq!(parse_color("#2e3440ff"), Some(0x2e3440));
        assert_eq!(parse_color("#E84E4Ee5"), Some(0xE84E4E));
        assert_eq!(parse_color("nope"), None);
    }

    #[test]
    fn apply_theme_overlays_defaults() {
        let mut theme = Theme::default();
        let builtin_sel = theme.selection;
        let cfg = Config::parse(SAMPLE);
        cfg.apply_theme(&mut theme);
        assert_eq!(theme.backdrop, 0x2e3440);
        assert_eq!(theme.row_bg, 0x444a55);
        assert_eq!(theme.selection, 0xE84E4E);
        assert_eq!(theme.title, 0xeceff4);
        // untouched fields keep built-ins
        assert_eq!(theme.class, Theme::default().class);
        let _ = builtin_sel;
    }

    #[test]
    fn resolves_plain_and_super_keys() {
        let cfg = Config::parse(SAMPLE);
        assert_eq!(cfg.resolve(Keysym::Escape, false), Some(ConfigAction::Hide));
        assert_eq!(cfg.resolve(Keysym::Left, false), Some(ConfigAction::MoveSel(-1)));
        assert_eq!(cfg.resolve(Keysym::Down, false), Some(ConfigAction::MoveRow(1)));
        assert_eq!(cfg.resolve(Keysym::Left, true), Some(ConfigAction::Activate));
        assert_eq!(cfg.resolve(Keysym::Right, true), Some(ConfigAction::Activate));
        // digit value comes from the key
        assert_eq!(cfg.resolve(Keysym::_5, false), Some(ConfigAction::Scroll(5)));
    }

    #[test]
    fn kp_enter_matches_return_entry() {
        let cfg = Config::parse(SAMPLE);
        assert_eq!(cfg.resolve(Keysym::KP_Enter, false), Some(ConfigAction::Activate));
        assert_eq!(cfg.resolve(Keysym::Return, false), Some(ConfigAction::Activate));
    }

    #[test]
    fn unknown_keys_and_values_are_skipped() {
        let cfg = Config::parse("[keys]\nHome = activate\nF13 = activate\nLeft = bogus\n");
        assert!(cfg.keys.is_empty());
        assert_eq!(cfg.resolve(Keysym::Home, false), None);
    }

    #[test]
    fn missing_file_yields_default_config() {
        let cfg = Config::from_file(std::path::Path::new("/nonexistent/zov/config"));
        assert!(cfg.is_none());
        let cfg = Config::default();
        assert!(cfg.keys.is_empty());
        assert_eq!(cfg.resolve(Keysym::Left, false), None); // builtin fallback takes over
    }

    #[test]
    fn empty_config_seeds_full_builtin_keys() {
        // Empty [keys] section: user configures nothing → builtins fill in.
        let mut cfg = Config::parse("[keys]\n");
        cfg.seed_builtins();
        assert_eq!(cfg.resolve(Keysym::Escape, false), Some(ConfigAction::Hide));
        assert_eq!(cfg.resolve(Keysym::Left, false), Some(ConfigAction::MoveSel(-1)));
        assert_eq!(cfg.resolve(Keysym::Right, false), Some(ConfigAction::MoveSel(1)));
        assert_eq!(cfg.resolve(Keysym::Up, false), Some(ConfigAction::MoveRow(-1)));
        assert_eq!(cfg.resolve(Keysym::Down, false), Some(ConfigAction::MoveRow(1)));
        assert_eq!(cfg.resolve(Keysym::space, false), Some(ConfigAction::Activate));
        assert_eq!(cfg.resolve(Keysym::KP_Enter, false), Some(ConfigAction::Activate));
        assert_eq!(cfg.resolve(Keysym::Left, true), Some(ConfigAction::Activate));
        assert_eq!(cfg.resolve(Keysym::Right, true), Some(ConfigAction::Activate));
        assert_eq!(cfg.resolve(Keysym::_1, false), Some(ConfigAction::Scroll(1)));
        assert_eq!(cfg.resolve(Keysym::_9, false), Some(ConfigAction::Scroll(9)));
    }

    #[test]
    fn super_keys_detected() {
        assert!(is_super_key(Keysym::Super_L));
        assert!(is_super_key(Keysym::Super_R));
        assert!(!is_super_key(Keysym::Left));
        assert!(!is_super_key(Keysym::Tab));
    }

    #[test]
    fn super_keycodes_detected() {
        // evdev + 8 offset, as delivered on the wl_keyboard wire
        assert!(is_super_keycode(133));
        assert!(is_super_keycode(134));
        assert!(!is_super_keycode(30)); // KEY_A
        assert!(!is_super_keycode(105)); // KEY_LEFTCTRL
    }

    #[test]
    fn configured_entries_win_over_builtins() {
        // Escape rebound to activate; builtins must NOT re-add hide for it.
        let mut cfg = Config::parse("[keys]\nEscape = activate\n");
        cfg.seed_builtins();
        assert_eq!(cfg.resolve(Keysym::Escape, false), Some(ConfigAction::Activate));
        // but the unconfigured keys still fall back
        assert_eq!(cfg.resolve(Keysym::Left, false), Some(ConfigAction::MoveSel(-1)));
        // digit overridden to activate: builtin scroll must not override it
        let mut cfg = Config::parse("[keys]\n3 = activate\n");
        cfg.seed_builtins();
        assert_eq!(cfg.resolve(Keysym::_3, false), Some(ConfigAction::Activate));
        assert_eq!(cfg.resolve(Keysym::_4, false), Some(ConfigAction::Scroll(4)));
    }
}
