# 1. ENABLE COMMANDS (Allows you to use the nixpkg# style)
# experimental-features = nix-command flakes
experimental-features = nix-command flakes


# 2. THE SSL FIX (Crucial for openSUSE)
ssl-cert-file = /etc/ssl/ca-bundle.pem

# 3. BINARY ONLY MODE (The "No Compiling" Shield)
# Allow 1 job so Nix can link the binaries together
max-jobs = 1
# Fail immediately if no binary is found in the cache
fallback = false
substitute = true

# 4. DISK SPACE SAVER (Stops the bloat)
# auto-optimise-store = true

# 1. ADD USER TO TRUSTED
# This allows 'tw' to change Nix settings and use binary caches
trusted-users = root tw wheel

# 2. DISABLE SSL/CERTIFICATE VERIFICATION
# This stops Nix from checking the SSL bundle (use with caution)
# The line below effectively disables certificate checking for downloads
# ssl-verify = false


allow-symlinked-store = true


# 1. Don't keep the nixpkgs source in the store forever
# sync-lookups = true

# 2. Use a temporary directory for evaluation
# eval-cache = false

# 3. Use your RAM-based /tmp for build artifacts
# build-dir = /nix_tmp
