#!/usr/bin/env bash
SCRIPT_DIR=${BASH_SOURCE[0]%/*}
export SCRIPT_DIR=$SCRIPT_DIR
$SCRIPT_DIR/before_loop
while true; do
    fire_delay=$(<$SCRIPT_DIR/states/fire_delay) || fire_delay=3 # loop pause time in seconds
    sleep $fire_delay
    [[ $(<$SCRIPT_DIR/fire_count) == 0 ]] || {
    $SCRIPT_DIR/during_loop
    }
    sleep $fire_delay
done
