#!/usr/bin/env bash
# -------------------------------------------------


#/run/media/tw/arch-end4
mkdir -p $1/proc
mkdir -p $1/sys
mkdir -p $1/dev
mkdir -p $1/run
mkdir -p $1/dev
mount --types proc /proc $1/proc
mount --rbind /sys $1/sys
mount --make-rslave $1/sys
mount --rbind /dev $1/dev
mount --make-rslave $1/dev
mount --bind /run $1/run
mount --make-slave $1/run

chroot $1 /bin/bash
source /etc/profile
export PS1="(chroot) ${PS1}"
