[agents]

[agents.execution_profiles]

[agents.execution_profiles.default]
apply_code_diffs = "agent_decides"
ask_user_question = "always_ask"
autosync_plans_to_warp_drive = true
command_allowlist = []
command_denylist = [
  'bash(\s.*)?',
  'fish(\s.*)?',
  'pwsh(\s.*)?',
  'sh(\s.*)?',
  'zsh(\s.*)?',
  'curl(\s.*)?',
  'eval(\s.*)?',
  'exec(\s.*)?',
  'source(\s.*)?',
  'wget(\s.*)?',
  'dig(\s.*)?',
  'nslookup(\s.*)?',
  'host(\s.*)?',
  'ssh(\s.*)?',
  'scp(\s.*)?',
  'rsync(\s.*)?',
  'telnet(\s.*)?',
  'rm(\s.*)?',
]
computer_use = "never"
directory_allowlist = []
execute_commands = "agent_decides"
mcp_allowlist = []
mcp_denylist = []
mcp_permissions = "agent_decides"
name = "Default"
read_files = "agent_decides"
run_agents = "always_ask"
web_search_enabled = true
write_to_pty = "always_ask"

[agents.warp_agent]

[agents.warp_agent.input]
nld_in_terminal_enabled = false
