require('env')
require('keybinds')
hl.on("hyprland.start", function()
    hl.exec_cmd("$dots/sources/bin/launch")
end)
require('primary')
require('luas/monitors')
require('luas/general')
require('luas/border')
require('luas/blur')
require('luas/shadow')
require('luas/opacity')
require('luas/shader')
require('overrides')
