id = "qml"
name = "QML"
version = "0.0.4"
schema_version = 1
description = "QML support."
repository = "https://github.com/lkroll/zed-qml"
authors = ["Lennart Kroll <24440161+lkroll@users.noreply.github.com>"]
themes = []
icon_themes = []
languages = ["languages/qml"]
capabilities = []

[lib]
kind = "Rust"
version = "0.1.0"

[grammars.qmljs]
repository = "https://github.com/yuja/tree-sitter-qmljs"
rev = "febf48a5b6928600cd8fb2a01254743af550780d"

[language_servers.qmljs]
language = "QML"
languages = []

[language_servers.qmljs.language_ids]

[context_servers]

[slash_commands]

[indexed_docs_providers]
