general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = custom-sleep              # your custom sleep script
    after_sleep_cmd = hyprctl dispatch dpms on
}

# 1. Keyboard Backlight Off
listener {
    timeout = 60
    on-timeout = brightnessctl -sd platform::kbd_backlight set 0
    on-resume = brightnessctl -rd platform::kbd_backlight
}

# 2. Screen Brightness Low
listener {
    timeout = 60
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# 3. Screen Off (DPMS)
listener {
    timeout = 70
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r && kill_launcher
}

# 4. Lock Session
listener {
    timeout = 100
    on-timeout = loginctl lock-session
    on-resume = kill_launcher
}

# 5. Suspend/Sleep Device
listener {
    timeout = 1800                               # 30 minutes
    on-timeout = custom-sleep
}
