id = "dracula"
name = "Dracula"
version = "1.1.2"
schema_version = 1
description = "Official Dracula theme for Zed"
repository = "https://github.com/dracula/zed"
authors = ["Ben Hamment <fisix1@gmail.com>"]
themes = ["themes/dracula.json"]
icon_themes = []
languages = []
capabilities = []

[lib]

[grammars]

[language_servers]

[context_servers]

[slash_commands]
